version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - ls -al
      - aws s3 cp build/ s3://continuous-deploy-front/
